### ISSUE TITLE
Modales administration

### ISSUE THREAD

**Issue by trztrztrz** [PierreSylvain/nao#11]
Reprendre ce format pour les modales:

![image](https://user-images.githubusercontent.com/15322010/31853775-c1c88df0-b68e-11e7-9693-2d61aff3e811.png)

Les boutons sont des boutons FLAT (sans contour)
Les messages de confirmation doivent être autre que oui et non (ex: ANNULER / CONFIRMER)

**Comment by PierreSylvain** [comment]
Fait sur : 

- Modération/Suppression commentaire
- Suppression article
