### ISSUE TITLE
Indiquer nb caractères max 

### ISSUE THREAD

**Issue by AlbertGaetan** [PierreSylvain/nao#26]
http://prntscr.com/h11gfn car l'utilisateur peut écrire plus (http://prntscr.com/h11grb) mais qu'une partie ne sera visible.

Il faudrait le mettre en italique par exemple et bloquer à X caractères (0 / 255 caractères)

**Comment by evaneox** [comment]
@AlbertGaetan la rubrique à propos n'est pas limité à 255 caractères normalement j'ai corriger le problème tu ne devrais plus avoir de limitation.
