### ISSUE TITLE
formatage des articles du blog par l'éditeur

### ISSUE THREAD

**Issue by trztrztrz** [PierreSylvain/nao#28]
PAS LA PRIORITE 

Mais penser si on a le temps à la fin du projet d'intégrer la possibilité de formater un peu les articles - niveaux de titre
- gras
- soulignage
- centrage

BB code ?
Editeur js ?
Wysiwyg ?
Plugin Tinymce ? https://www.tinymce.com/

**Comment by evaneox** [comment]
https://summernote.org/

**Comment by PierreSylvain** [comment]
Utilisation de MaterialNote (https://github.com/Cerealkillerway/materialNote)
Summernote ne fonctionne qu'avec Bootstrap.
Gras, Italique, Souligné, Liste, Formatage (Gauche, droite, centré, justifié)
