### ISSUE TITLE
Notification rejet obs à l'admin

### ISSUE THREAD

**Issue by AlbertGaetan** [PierreSylvain/nao#38]
http://prntscr.com/h33mnw

Ici, il n'y a pas le nom de l'utilisateur concerné, l'admin ne peut donc pas le bannir ou autre. Il serait mieux de mettre : 
De {nom_naturaliste} concernant l'utilisateur {nom_utilisateur}

Uniquement pour les notifs de l'admin

**Comment by PierreSylvain** [comment]
Le titre a été ajouté au début du texte saisi par le naturaliste, parce que la structure actuelle ne permet pas de gérer un titre de notification.

![image](https://user-images.githubusercontent.com/27854918/32135366-47f9b2c2-bbfe-11e7-87e1-15fae0f46e74.png)
