### ISSUE TITLE
erreur 404 page obs

### ISSUE THREAD

**Issue by AlbertGaetan** [PierreSylvain/nao#42]
https://projet.evaneox.com/projet5/observation/

http://prntscr.com/h3l7qn

**Comment by AlbertGaetan** [comment]
Voir pour faire une redirection de observation vers mes observations ?

**Comment by AlbertGaetan** [comment]
Redirection sur la carte

**Comment by evaneox** [comment]
Les observations sont disponibles sur la page /observation
