### ISSUE TITLE
Connexion par réseaux sociaux

### ISSUE THREAD

**Issue by trztrztrz** [PierreSylvain/nao#43]
Je ne sais pas si ça a été fait ou pas alors je mets l'issue pour ne pas oublier

- Facebook > aucune action au clic sur le bouton 

- Google > après sélection du compte dans la modale >> erreur 400
https://screenshots.firefox.com/yPJCAJoQr38x4ovB/accounts.google.com

**Comment by PierreSylvain** [comment]
Corrigé
Paramétrage de Facebook
Paramétrage de Google
