### ISSUE TITLE
gestion des utlisateurs : upgrade impossible

### ISSUE THREAD

**Issue by trztrztrz** [PierreSylvain/nao#50]
en admin, je ne parviens pas à débloquer et upgrader les observateurs bloqué (ex: observateur 4)

Après changement et validation, ça revient à la situation initiale.

Pas de pb avec les "vrais" comptes, testé avec le compte de  jérémy par ex

**Comment by PierreSylvain** [comment]
Les noms des utilisateurs qui étaient créé automatiquement n'étaient pas compatibles avec les restrictions appliquées au niveau des noms.
Les créations à présent utilise une liste aléatoire de noms.
@evaneox il est nécessaire de recharger les utilisateurs ou de modifier directement dans la base le champ name.

![image](https://user-images.githubusercontent.com/27854918/32395945-95aca6d4-c0e3-11e7-815b-d718045bb87b.png)

**Comment by evaneox** [comment]
J'ai retirer les faux utilisateurs de la base de données, le problème ne devrait pas se reproduire.
