### ISSUE TITLE
notifications

### ISSUE THREAD

**Issue by trztrztrz** [PierreSylvain/nao#55]
1) lorsqu'un naturaliste valide une observation ou un commentaire, le user ne reçoit pas de notif

2) Lorsqu'un naturaliste refuse une obs, le user reçoit bien une notif avec le commentaire de refus rédigé par le naturaliste. Mais on ne sait pas de quelle obs on parle. Peut-ton rajouter une petite mention avec le nom de l'espèce + la date pour orienter un peu l'observateur ?

**Comment by PierreSylvain** [comment]
**Notification à l'administrateur**
![image](https://user-images.githubusercontent.com/27854918/32395154-4ca234d4-c0e0-11e7-8f09-9d6afbe0ac87.png)

**Notification à l'observateur**
![image](https://user-images.githubusercontent.com/27854918/32395183-64ca04ec-c0e0-11e7-90c0-72b737f3a210.png)
