### ISSUE TITLE
Bug sur la réinitialisation des mdp

### ISSUE THREAD

**Issue by AlbertGaetan** [PierreSylvain/nao#61]
La réinitialisation de mot de passe fonctionne sur les adresses"normales" cependant pas sur ces adresses : 
- albert.gaetan@gmail.com
- albert.gaetan@webteck.fr 

La réinitialisation ne fonctionne pas.

2 hypothèses : 
- Problème avec les emails qui comportent un .
- Problème avec les emails ayant le même utilisateur

**Comment by evaneox** [comment]
> Problème avec les emails qui comportent un 

Aucun problème avec le compte "projetocr.nao@gmail.com" 

> Problème avec les emails ayant le même utilisateur

Il n'y a pas de vérification faite pour les utilisateurs

J'ai supprimer les deux comptes, si tu peut de nouveau essayer quand tu a le temps et me faire un retour.

**Comment by evaneox** [comment]
Il n'est plus possible de demander de réinitialiser le mot de passe pour les compte issues de Facebook ou google.
