### ISSUE TITLE
CSS

### ISSUE THREAD

**Issue by trztrztrz** [PierreSylvain/nao#7]
Plusieurs pb de css dans le dashboard admin :
voir maquette pour visuels

remarques :
- [ ] Boutons flottants > btn-floating btn-large (qui donne 54px / icône 24px par défaut) : concerne TOUS les btn-floating

**Comment by PierreSylvain** [comment]
Fait sur : 

- Ajout image dans gestion article (ajou et création)
- Ajour article dans liste des articles.
